/* SKOOT messages */

# define SKOOT_MAPURL		1
# define SKOOT_ARTURL		2
# define SKOOT_REALMURL		3
# define SKOOT_BIGMAPURL	4
# define SKOOT_COMPASS		5
# define SKOOT_ANYURL           6

# define SKOOT_PLAYERS_CLEAR	20
# define SKOOT_PLAYERS_ENTER	21
# define SKOOT_PLAYERS_LEAVE	22

# define SKOOT_OBJECTS_CLEAR	30
# define SKOOT_OBJECTS_ENTER	31
# define SKOOT_OBJECTS_LEAVE	32

# define SKOOT_INVENTORY_CLEAR	40
# define SKOOT_INVENTORY_ENTER	41
# define SKOOT_INVENTORY_LEAVE	42

# define SKOOT_EXITS_CLEAR	50
# define SKOOT_EXITS_ADD	51

# define SKOOT_CHATMODE_ON	60
# define SKOOT_CHATMODE_OFF	61

# define SKOOT_TOOL_SOURCE	70

/* Messages for Jitsi-based Audio Chat */
# define SKOOT_CHAT_SET_ROOM    80
# define SKOOT_CHAT_SET_MUTED   81
# define SKOOT_CHAT_SET_NAME    82
