# define COMBINABLE_ENABLED	0x01
# define COMBINABLE_DISCRETE	0x02
# define COMBINABLE_BY_WEIGHT	0x04

# define CONTENT_GROUP_OBJ	0
# define CONTENT_GROUP_PROX	1
# define CONTENT_GROUP_STANCE	2
# define CONTENT_GROUP_PREP	3
# define CONTENT_GROUP_FLAGS	4

# define CONTENT_FLAG_WEAR	0x01
