#list# etc etc is generated by some sort of stamp process.

methods

	Some sort of way for Merry scripts to call back into LPC in a
	controlled way.

	Especially check out AssistD and Chatlines

properties

	Magic properties that call back into LPC to set or get values

SID

	This is a way for object state to be imported and exported.

	The SIDs are used to create "forms" that woe developers can use to
	check states and select stuff.

	They also allow an object's state to be formatted into XML.
