"name": DGD Smoke Test

"on": push

jobs:
  boot-test:
    name: DGD server boot-up test
    runs-on: ubuntu-latest

    steps:
      - name: "Check out code"
        uses: actions/checkout@v2

      - name: "Set up Ruby code"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Cache DGD
        uses: actions/cache@v2
        env:
          cache-name: cache-built-dgd
        with:
          path: dgd
          key: built-dgd-${{ runner.os }}-${{ env.cache-name }}-2

      - name: Build DGD
        run: ./deploy_scripts/ghactions/build_dgd.sh

      - name: Run SkotOS server
        run: ./dgd/bin/dgd skotos.dgd >log/dgd_server.txt &

      - name: Fail if SkotOS doesn't start
        run: pgrep -f "dgd/bin/dgd skotos.dgd"

      - name: Clone wafer
        run: git clone https://github.com/ChatTheatre/wafer.git

      - name: Run wafer
        run: cd wafer && bundle && ruby -Ilib ./exe/wafer 2>&1 &

      - name: Show wafer log
        run: cat log/wafer_log.txt || echo "Could not find wafer_log.txt"

      - name: Test that wafer is running successfully
        run: pgrep -f "rackup -p 2072"

      - name: Wait for SkotOS to finish booting.
        run: ./deploy_scripts/shared/wait_for_full_boot.sh

      - name: SkotOS log
        run: cat log/dgd_server.txt

      - name: Run telnet tests
        run: ./test/telnet_wiztool/test_1_reasonable.rb

      - name: Shut down SkotOS server
        run: ./deploy_scripts/shared/stop_all_dgd.sh
